### ISSUE TITLE
Auth service groups use IAM roles which have pre-determined ARNs

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-auth#6]
Motivation: the current ARNs generated by this stack include random strings and that seems brittle for requesting those roles be added to our bucket policy

These can either be existing roles that we look up or have names that are statically defined along with the name of the veda-auth stack 

Alexandra's suggestion: Pass existing role ARNs in MCP as environment variables in the deployment to be used for the groups.

Tasks:
- [ ] Try to deploy changes to dev stack

**Comment by anayeaye** [comment]
[veda-auth pr 10](https://github.com/NASA-IMPACT/veda-auth/pull/10) is merged and the project can now be deployed with service groups that assume a pre-determined ARN (of an existing role)
